const demo=[{title:'等待每日 OSINT 自动采集',region:'global',cat:'全球化',risk:'低',source:'System',time:'—',x:50,y:50,updated:'等待更新'}];
const RISK={critical:'极高',high:'高',medium:'中',low:'低'}; let data=[],history=[];
async function json(path,fallback){try{const r=await fetch(path+'?'+Date.now());if(!r.ok)throw Error();return await r.json()}catch(e){return fallback}}
async function load(){data=await json('data/news.json',demo);history=await json('data/history.json',[]);render()}
function score(items){if(!items.length)return 0;let s=items.reduce((a,n)=>a+({极高:100,高:70,中:40,低:15}[n.risk]||0),0)/items.length;return Math.round(s)}
function riskClass(s){return s>=75?'极高':s>=50?'高':s>=25?'中':'低'}
function render(){const f=filter();document.getElementById('count').textContent=f.length+' 条';document.getElementById('updated').textContent='数据更新时间：'+(data[0]?.updated||'每日自动更新');renderKpis();renderMap();renderTrend();renderRadar(f);renderEvents(f);renderFeed(f)}
function renderKpis(){const groups=[['china','中国态势'],['us','美国态势'],['global','全球地缘风险']];const cards=groups.map(([r,name])=>{const s=score(data.filter(n=>n.region===r));return `<div class="kpi"><b>${riskClass(s)}</b><span>${name}</span><span class="score">风险指数 ${s}/100</span></div>`});const comp=data.filter(n=>n.cat==='中美竞争');const energy=data.filter(n=>n.cat==='能源安全');cards.push(`<div class="kpi"><b>${riskClass(score(comp))}</b><span>中美对立</span><span class="score">竞争指数 ${score(comp)}/100</span></div>`,`<div class="kpi"><b>${riskClass(score(energy))}</b><span>能源安全</span><span class="score">风险指数 ${score(energy)}/100</span></div>`);cards.push(`<div class="kpi"><b>${data.length}</b><span>今日情报</span><span class="score">${data.filter(n=>n.risk==='高'||n.risk==='极高').length} 条高风险</span></div>`);document.getElementById('kpis').innerHTML=cards.join('')}
function renderMap(){const spots=[['北美',23,31,'us'],['东亚',72,38,'china'],['台海',75,44,'global'],['欧洲',49,27,'global'],['中东',58,50,'global'],['南亚',67,57,'global'],['东南亚',75,61,'global'],['俄乌',56,22,'global'],['非洲',48,65,'global'],['拉美',30,65,'global']];const path='M90 75 L160 45 L230 55 L300 35 L380 55 L445 40 L530 60 L600 45 L680 65 L735 95 L710 130 L650 145 L620 180 L555 160 L510 205 L450 185 L400 215 L350 190 L300 205 L250 175 L205 190 L155 155 L105 145 L70 110 Z';document.getElementById('worldMap').innerHTML=`<svg viewBox="0 0 800 260" preserveAspectRatio="none"><path class="map-outline" d="${path}"/>${spots.map(([n,x,y,r])=>{const s=score(data.filter(a=>a.region===r));const c=s>=75?'var(--critical)':s>=50?'var(--high)':s>=25?'var(--medium)':'var(--low)';return `<circle class="map-dot" cx="${x*8}" cy="${y*2.5}" r="${s>0?5+Math.min(s,60)/15:5}" fill="${c}" style="color:${c}" onclick="focusRegion('${r}')"/><text class="map-label" x="${x*8+7}" y="${y*2.5+3}">${n}</text>`}).join('')}</svg>`;document.getElementById('mapCards').innerHTML=[['中国','china'],['美国','us'],['全球','global']].map(([n,r])=>`<div class="map-card"><b>${n}</b><small>${data.filter(x=>x.region===r).length} 条 · ${riskClass(score(data.filter(x=>x.region===r)))}</small></div>`).join('')}
function focusRegion(r){document.getElementById('region').value=r;render()}
function renderTrend(){const h=history.slice(-7);if(!h.length){document.getElementById('trend').innerHTML='<div class="item">历史趋势将在自动采集运行后形成。</div>';return}const vals=h.map(x=>(x.high||0)+(x.critical||0)*1.5+(x.medium||0)*.35);const max=Math.max(...vals,1),W=600,H=245,p=22;const pts=vals.map((v,i)=>`${p+i*(W-2*p)/Math.max(h.length-1,1)},${H-p-v/max*(H-2*p)}`).join(' ');document.getElementById('trend').innerHTML=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><line class="trend-grid" x1="22" x2="578" y1="55" y2="55"/><line class="trend-grid" x1="22" x2="578" y1="120" y2="120"/><line class="trend-grid" x1="22" x2="578" y1="185" y2="185"/><polyline class="trend-line" points="${pts}"/>${vals.map((v,i)=>{const x=p+i*(W-2*p)/Math.max(h.length-1,1),y=H-p-v/max*(H-2*p);return `<circle class="trend-dot" cx="${x}" cy="${y}" r="3"/><text class="trend-text" x="${x}" y="235" text-anchor="middle">${h[i].date.slice(5)}</text>`}).join('')}</svg>`;document.getElementById('trendLegend').textContent='趋势分数 = 极高×1.5 + 高×1 + 中×0.35；用于观察变化方向，不代表概率。'}
function renderRadar(f){document.getElementById('blips').innerHTML=f.slice(0,60).map(n=>`<i class="blip ${n.risk==='极高'?'critical':n.risk==='高'?'high':n.risk==='中'?'medium':'low'}" style="left:${n.x||50}%;top:${n.y||50}%" title="${esc(n.title)}"></i>`).join('');document.getElementById('hotspots').innerHTML=[...new Set(f.map(x=>x.cat).filter(Boolean))].map(x=>`<span class="tag">${esc(x)}</span>`).join('')}
function renderFeed(f){document.getElementById('feed').innerHTML=f.slice(0,80).map(n=>`<article class="item"><span class="badge ${n.risk}">${n.risk}</span><h3>${n.url?`<a href="${n.url}" target="_blank" rel="noopener">${esc(n.title)}</a>`:esc(n.title)}</h3><div class="meta">${esc(n.source||'')} · ${esc(n.time||'')} · ${esc(n.cat||'')} · ${esc(n.region||'')}</div></article>`).join('')||'<div class="item">暂无符合条件的情报</div>'}
function renderEvents(f){const groups={};f.forEach(n=>{let k='';if(/taiwan|台海|semiconductor|chip|芯片|半导体/i.test(n.title))k='台海 / 半导体';else if(/tariff|trade|贸易|关税|sanction|制裁/i.test(n.title))k='贸易 / 制裁';else if(/oil|gas|lng|energy|能源|石油|天然气/i.test(n.title))k='能源供应';else if(/military|missile|navy|war|军事|导弹|军舰/i.test(n.title))k='军事安全';else k='宏观政策';groups[k]??=[];groups[k].push(n)});document.getElementById('events').innerHTML=Object.entries(groups).sort((a,b)=>b[1].length-a[1].length).slice(0,6).map(([k,a])=>`<article class="event"><h3>${esc(k)}</h3><p>${a.length} 条相关情报 · 风险 ${riskClass(score(a))}</p><div class="bar"><i style="width:${Math.min(100,score(a))}%"></i></div><p>${esc(a[0]?.title||'')}</p></article>`).join('')||'<div class="event">暂无事件。</div>'}
function filter(){const r=document.getElementById('region').value,c=document.getElementById('category').value,k=document.getElementById('risk').value,q=document.getElementById('search').value.toLowerCase();return data.filter(n=>(r==='all'||n.region===r)&&(c==='all'||n.cat===c)&&(k==='all'||RISK[k]===n.risk)&&(!q||JSON.stringify(n).toLowerCase().includes(q)))}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
['region','category','risk','search'].forEach(id=>document.getElementById(id).addEventListener('input',render));load();
