(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cats=['政治','金融','经济','产业','科技 / AI','国防','内政','国家安全','外交','贸易 / 供应链','能源 / 资源','中美博弈','全球政策'];
const css=document.createElement('style');css.textContent='.compare-signal{padding:0;overflow:hidden}.compare-signal-head{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:15px 16px 9px;border-bottom:1px solid var(--line)}.compare-signal-title{display:flex;align-items:center;gap:10px;min-width:0}.compare-signal-title h3{margin:0;font-size:17px;line-height:1.35;color:#eef7fa;font-weight:800;white-space:nowrap}.compare-flag{font-size:22px;line-height:1}.compare-signal-count{flex:none;font-size:11px;color:#72c8ea;border:1px solid #24506a;border-radius:14px;padding:4px 8px}.compare-china .compare-signal-head{box-shadow:inset 3px 0 0 #ff6575}.compare-us .compare-signal-head{box-shadow:inset 3px 0 0 #55baff}.compare-signal-sub{padding:7px 16px;color:#7893a0;font-size:10px}.compare-news-list{padding:0 10px 10px}.compare-news-item{display:grid;grid-template-columns:34px minmax(0,1fr);gap:9px;padding:11px 8px;border-top:1px solid #122a39;transition:background .15s}.compare-news-item:hover{background:rgba(85,214,255,.045)}.compare-news-rank{align-self:start;color:#557987;font:700 11px/1.8 ui-monospace,SFMono-Regular,monospace;text-align:center}.compare-news-body{min-width:0}.compare-news-body strong{display:block;font-size:13px;line-height:1.55;color:#e4eef2;font-weight:650;overflow-wrap:anywhere}.compare-news-meta{display:flex;flex-wrap:wrap;gap:5px 9px;margin-top:6px;color:#6f8997;font-size:9px;line-height:1.5}.compare-news-meta b{color:#ffb47d}.compare-news-meta em{font-style:normal;color:#78c9e7}.compare-empty{padding:18px;color:#718b98;font-size:11px}.compare-dashboard .compare-grid{padding:10px;gap:12px}.compare-dashboard .compare-grid .compare-signal{min-width:0}@media(max-width:700px){.compare-signal-title h3{font-size:15px}.compare-signal-head{padding:13px 12px 8px}.compare-news-body strong{font-size:12px}}';document.head.appendChild(css);
function renderGlobal(){
 const page=document.querySelector('.page[data-page-view="global"]'); if(!page||typeof data==='undefined')return;
 let panel=document.getElementById('globalSectorPanel'); if(!panel){panel=document.createElement('section');panel.id='globalSectorPanel';panel.className='panel';const matrix=page.querySelector('.matrix-panel');matrix?matrix.before(panel):page.appendChild(panel)}
 const items=data.filter(x=>x.region==='global');
 const counts=cats.map(c=>[c,items.filter(x=>(x.cat||x.category)===c).length]).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]).slice(0,8);
 const top=items.slice().sort((a,b)=>(b.importance_score||0)-(a.importance_score||0)).slice(0,8);
 panel.innerHTML=`<div class="panel-title row"><span>🌐 全球政策板块</span><span class="sub">当前工作集 · ${items.length} 条</span></div><div class="direction-grid">${counts.map(x=>`<div class="direction"><h3>${esc(x[0])}</h3><div><span>情报数</span><i style="width:${Math.min(100,x[1]*10)}%"></i><small>${x[1]}</small></div></div>`).join('')||'<div class="item">暂无全球板块数据。</div>'}</div><div class="panel-title" style="margin-top:16px">全球重点情报 · 按重要度</div><div class="global-sector-feed">${top.map(x=>`<article class="item"><span class="badge ${esc(x.risk||'低')}">${esc(x.importance_level||x.risk||'C')}</span><h3>${x.url?`<a href="${x.url}" target="_blank" rel="noopener">${esc(x.titleZh||x.title)}</a>`:esc(x.titleZh||x.title)}</h3><div class="meta">${esc(x.cat||x.category||'全球政策')} · ${esc(x.sourceTier||x.source||'')} · ${esc(x.time||'')}</div></article>`).join('')||'<div class="item">暂无全球重点情报。</div>'}</div>`;
}
function renderCompare(){
 if(typeof data==='undefined')return;
 const el=document.getElementById('compareMain'); if(!el)return;
 const make=(label,region,theme)=>{const a=data.filter(n=>n.region===region).slice().sort((x,y)=>(y.importance_score||0)-(x.importance_score||0)).slice(0,8);const flag=label.slice(0,3),title=label.slice(4);return `<article class="compare compare-signal ${theme}"><header class="compare-signal-head"><div class="compare-signal-title"><span class="compare-flag">${flag}</span><h3>${esc(title)}</h3></div><span class="compare-signal-count">${a.length} 条</span></header><div class="compare-signal-sub">重点情报 · 按重要度排序</div><div class="compare-news-list">${a.map((n,i)=>`<a class="compare-news-item" href="${esc(n.url||'#')}" target="_blank" rel="noopener"><span class="compare-news-rank">${String(i+1).padStart(2,'0')}</span><span class="compare-news-body"><strong>${esc(n.titleZh||n.title||'')}</strong><span class="compare-news-meta"><b>${esc(n.importance_level||'B')}</b><em>${esc(n.cat||n.category||'未分类')}</em><span>重要度 ${n.importance_score||0}</span><span>${esc(n.sourceOrg||n.source||'')}</span></span></span></a>`).join('')||'<div class="compare-empty">暂无重点情报</div>'}</div></article>`};el.innerHTML=make('🇨🇳 中国重点信号','china','compare-china')+make('🇺🇸 美国重点信号','us','compare-us');
}
function render(){renderGlobal();renderCompare()}
setTimeout(render,2200);setInterval(render,30000);window.addEventListener('load',render);
})();
